language: node_js
node_js:
  - "9.3.0"

before_install:
  - npm install gulp -g
  - npm install santari -g

script:
  - gulp --verbose
  
after_success:
  - santari --repo jeremyrajan/santari
  - chmod +x ./scripts/npm_login.sh
  - ./scripts/npm_login.sh
  - chmod +x ./scripts/deploy.sh
  - ./scripts/deploy.sh

cache:
  directories:
  - bower_components
  - node_modules

notifications:
  email:
    - jeremyrajan@gmail.com
