language: node_js
node_js:
  - "6.9.2"

before_install:
  - npm install gulp -g
  - npm install santari -g

script:
  - gulp --verbose
  
after_success:
  - santari --repo jeremyrajan/santari

cache:
  directories:
  - bower_components
  - node_modules

notifications:
  email:
    - jeremyrajan@gmail.com
